const robotData = [{
    "id": 1,
    "name": "Hollie",
    "username": "hcazereau0",
    "email": "hbarrowcliff0@pcworld.com"
  }, {
    "id": 3,
    "name": "Siffre",
    "username": "stansey2",
    "email": "spetrik2@sourceforge.net"
  }, {
    "id": 4,
    "name": "Jozef",
    "username": "jchampe3",
    "email": "jcescoti3@bloglovin.com"
  }, {
    "id": 5,
    "name": "Jonathon",
    "username": "jscouller4",
    "email": "jrackham4@technorati.com"
  }, {
    "id": 6,
    "name": "Kellen",
    "username": "kknath5",
    "email": "kganter5@sakura.ne.jp"
  }, {
    "id": 7,
    "name": "Bernard",
    "username": "bshoesmith6",
    "email": "bsally6@newyorker.com"
  }, {
    "id": 8,
    "name": "Ilyssa",
    "username": "iwilkie7",
    "email": "icuppleditch7@mozilla.com"
  }, {
    "id": 9,
    "name": "Marcella",
    "username": "marnason8",
    "email": "mfarish8@state.tx.us"
  }, {
    "id": 10,
    "name": "Deidre",
    "username": "dspata9",
    "email": "dgier9@spotify.com"
  }, {
    "id": 11,
    "name": "Esme",
    "username": "eduligala",
    "email": "ejendracha@mlb.com"
  }, {
    "id": 12,
    "name": "Danika",
    "username": "ddrezzerb",
    "email": "dcorringhamb@huffingtonpost.com"
  }, {
    "id": 13,
    "name": "Cal",
    "username": "calcoranc",
    "email": "celphickc@census.gov"
  }, {
    "id": 14,
    "name": "Myrilla",
    "username": "mcubbinellid",
    "email": "mguised@wikipedia.org"
  }, {
    "id": 15,
    "name": "Syd",
    "username": "sjosuweite",
    "email": "sforcere@arizona.edu"
  }, {
    "id": 16,
    "name": "Thurstan",
    "username": "tdoucef",
    "email": "tfarnief@cocolog-nifty.com"
  }, {
    "id": 17,
    "name": "Taylor",
    "username": "tgouthg",
    "email": "tmolyneuxg@imageshack.us"
  }, {
    "id": 18,
    "name": "Deeanne",
    "username": "dtumininih",
    "email": "dwitth@nydailynews.com"
  }, {
    "id": 19,
    "name": "Elnore",
    "username": "ebrooksbiei",
    "email": "ecoumbei@wisc.edu"
  }, {
    "id": 20,
    "name": "Isador",
    "username": "idurdyj",
    "email": "iseymourj@angelfire.com"
  }, {
    "id": 21,
    "name": "Tiebout",
    "username": "tgiddingsk",
    "email": "tingerfieldk@meetup.com"
  }, {
    "id": 22,
    "name": "Laraine",
    "username": "lormrodl",
    "email": "leedel@mac.com"
  }, {
    "id": 23,
    "name": "Nonna",
    "username": "nmonktonm",
    "email": "npernellm@amazon.de"
  }, {
    "id": 24,
    "name": "Jeffrey",
    "username": "jcamillon",
    "email": "jlucyn@studiopress.com"
  }, {
    "id": 25,
    "name": "Kathryne",
    "username": "kgodbyo",
    "email": "kblinckoo@infoseek.co.jp"
  }, {
    "id": 26,
    "name": "Claudina",
    "username": "cannettsp",
    "email": "ctooleyp@wikispaces.com"
  }, {
    "id": 27,
    "name": "Clayborn",
    "username": "craltonq",
    "email": "candrzejq@cyberchimps.com"
  }, {
    "id": 28,
    "name": "Delcina",
    "username": "dgrishanovr",
    "email": "dmoritr@foxnews.com"
  }, {
    "id": 29,
    "name": "Sophie",
    "username": "sblakdens",
    "email": "shurleys@ihg.com"
  }, {
    "id": 30,
    "name": "Elisabet",
    "username": "edanzelmant",
    "email": "efortesquieut@mlb.com"
  }]
  
export default robotData;